config/routes.rb
Rails.application.routes.draw do
  get 'no_user/index'
  get 'tipo_producto/index'
  get 'permiso/index'
  get 'rol/index'
  
  devise_for :views
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :no_user
  resources :tipo_producto
  resources :permiso
  resources :rol
  resources :error404
  resources :usuarios
  resources :references  
  resources :divisions
  resources :cargos
  resources :ubicacions
  get 'ubicacionProveedores/:proveedor_id' , to: 'ubicacions#edit2', :as => 'editUbicacionesProveedor'#sin uso
  get 'proveedor/:usuario_id' , to:'usuarios#nuevoProveedor' , :as => 'proveedorNuevo'
  post 'crearProveedor' , to:'usuarios#crearProveedor',:as =>'crearProveedor'
  get 'ubicacion/:proveedor_id' , to:'usuarios#nuevaUbicacion',:as =>'nuevaUbicacion'
  post 'crearUbicacion' , to:'usuarios#crearUbicacion',:as =>'crearUbicacion'
  get 'referencia/:proveedor_id' , to:'usuarios#nuevaReferencia',:as =>'nuevaReferencia'
  post 'crearReferencia' , to:'usuarios#crearReferencia',:as =>'crearReferencia'
  get 'proveedores/reporte' , to:'proveedors#reporte', :as => 'reporteProveedores'




  
  resources :productos
  resources :linea_requesicions, only: [:index]
  resources :requesicions
  get 'buscador_productos/:criterio', to: 'productos#buscador'
  post 'agregar_producto_requesicion', to: 'requesicions#agregar_producto'
  get 'requesicions/:id/observacion', to: 'requesicions#observacion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :proveedors
  get 'proveedors_user/:id/:usuario_id' , to: 'proveedors#show'
  # Defines the root path route ("/")
  # root "articles#index"
  #resources :cotizacions, only: [:index] rol de proveedor
  resources :linea_cotizacions, only: [:index]
  get 'cotizaciones_proveedor/:id', to: 'cotizacions#new' #rol de proveedor  
  get 'cotizaciones', to: 'cotizacions#evaluar'#rol de autorizador
  get 'cotizaciones_proveedor', to: 'cotizacions#index' #rol de proveedor
  get 'cotizaciones/:id', to: 'cotizacions#detalles' #rol autorizador
  post 'guardar_cotizacion/:id', to: 'cotizacions#create' #rol de proveedor
  post 'guardar_linea_cotizacion', to: 'cotizacions#lineas_cotizacion' #rol de proveedor
  post 'aprobar_cotizacion', to: 'cotizacions#aprobar' #rol autorizador

  get 'reporte/prod_ordenados', to: 'reporg#productos_ordenados'      #reporte por productos ordenados  Gerente
  get 'reporte/compras_categorias', to: 'reporg#compras_categorias'   #Reporte de montos de compra por categorias Gerente
  get 'reporte/stock_productos', to: 'productos#reporte_stock'
  get 'evaluaciones', to: 'evaluacions#index'
  get 'evaluacions/new/:id', to: 'evaluacions#new'
  post 'evaluacions/create', to: 'evaluacions#create'
  resources :login
  get 'login/index', to: 'login#index'

end

app/models/ubicacion.rb
class Ubicacion < ApplicationRecord
  belongs_to :proveedor

  has_one_attached:local
  has_one_attached:mapa

  validates_presence_of :nombre, presence: true,:message => "->El nombre de de la ubicacion no puede estar vacio"  
  validates_presence_of :direccion, presence: true,:message => "->La direccion no puede estar vacia"
  validates_presence_of :local, presence: true,:message => "-> Archivo de imagen de local no cargada"
  validates_presence_of :mapa, presence: true,:message => "-> Archivo de imagen en mapa no cargada"
end

app/controllers/ubicacions_controller.rb
class UbicacionsController < ApplicationController
  before_action :set_ubicacion, only: %i[ show edit update destroy ]

  # GET /ubicacions or /ubicacions.json
  def index
    @ubicacions = Ubicacion.all
  end

  # GET /ubicacions/1 or /ubicacions/1.json
  def show
  end

  # GET /ubicacions/new
  def new
    @ubicacion = Ubicacion.new
    @proveedors=Proveedor.all
  end

  # GET /ubicacions/1/edit
  def edit
    @proveedors=Proveedor.all#usado en la transicion de edit2 a edit para mostrar el combo de proveedores
  end

  #en des uso, responde a una url pero no lo termine
  def edit2
    @var =params[:proveedor_id]#aqui resivo el id del proveedor
    @ubicacionesDelProveedor=Ubicacion.where(:proveedor_id =>@var)
    @proveedors=Proveedor.all
    render :editDeProveedor#aqui render la pagina con todos los valores
  end 

  # POST /ubicacions or /ubicacions.json
  def create
    @ubicacion = Ubicacion.new(ubicacion_params)
    @proveedors=Proveedor.all
    

    respond_to do |format|
      if @ubicacion.save
        format.html { redirect_to ubicacion_url(@ubicacion), notice: "Ubicacion was successfully created." }
        format.json { render :show, status: :created, location: @ubicacion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ubicacions/1 or /ubicacions/1.json
  def update
    @proveedors=Proveedor.all
    respond_to do |format|
      if @ubicacion.update(ubicacion_params)
        format.html { redirect_to ubicacion_url(@ubicacion), notice: "Ubicacion was successfully updated." }
        format.json { render :show, status: :ok, location: @ubicacion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ubicacions/1 or /ubicacions/1.json
  def destroy
    @ubicacion.destroy
    id=params[:proveedor_id]
    respond_to do |format|
      #format.html { redirect_to ubicacions_url, notice: "Ubicacion was successfully destroyed." }
      format.html { redirect_to ubicacions_url, notice: "Ubicacion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ubicacion
      @ubicacion = Ubicacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ubicacion_params
      params.require(:ubicacion).permit(:nombre, :direccion, :proveedor_id,:local,:mapa)
    end
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper

    def buscarNombreProveedor(id)
        (Proveedor.find(id)).compania
    end

    def buscarLogoProveedor(id)
        (Proveedor.find(id)).logo
    end
end

app/views/ubicacions/_form.html.erb
<div class="container ">
  <div class="card-body shadow-lg">
    <%= form_with(model: ubicacion) do |form| %>
      <div class="form-group row mb-3">
      <% if ubicacion.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(ubicacion.errors.count, "error") %> No se puede continuar por los siguientes errores:</h2>

          <ul>
            <% ubicacion.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="form-group row mb-3">
      <%= form.label 'Proveedor:', class:'col-sm-2 ' %>
      <div class="col-sm-4">
        <%= form.collection_select :proveedor_id,@proveedors,"id","compania",class:'form-select'   %>
      </div>
    </div>

    <div class="form-group row  mb-3 ">
      <%= form.label :nombre, class:'col-sm-2', style: "display: block"   %>
      <div class="col-sm-4">
        <%= form.text_field :nombre ,id:"compania" ,class:"form-control" %>
        
      </div>

    </div>

    <div class="form-group row  mb-3 ">
      <%= form.label :direccion, class:'col-sm-2', style: "display: block"   %>
      <div class="col-sm-4">
        <%= form.text_field :direccion ,id:"compania" ,class:"form-control" %>
        
      </div>

    </div>
    
    <div class="form-group row mb-3">
      <%= form.label :local,class:'col-sm-2', style: "display: block" %>
      <div class="col-sm-4">
        <%= form.file_field :local, class:'form-control'  %>
        <p></p>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :mapa,class:'col-sm-2', style: "display: block" %>
      <div class="col-sm-4">
        <%= form.file_field :mapa, class:'form-control'  %>
        <p></p>
      </div>

    </div>

    <button type="submit" name="button" class='btn btn-primary'>
      <span>Guardar</span>
    </button>

    <%= yield(:boton) %>
  <% end %>
</div>

app/views/ubicacions/_formUbicacionProveedor.html.erb
<div class="container ">
  <div class="card-body shadow-lg">
    <%= form_with(model: ubicacion) do |form| %>
      <div class="form-group row mb-3">
        <% if ubicacion.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(ubicacion.errors.count, "error") %> prohibited this ubicacion from being saved:</h2>

            <ul>
              <% ubicacion.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>

      <div class="form-group row mb-3">
        <%= form.label 'Nombre de ubicacion:', class:'col-sm-2 ' %>
        <div class="col-sm-4">
          <%= form.text_field :nombre ,id:"compania" ,class:"form-control" %>
        </div>
      </div>

      <div class="form-group row mb-3">
        <%= form.label 'Direccion de ubicacion:', class:'col-sm-2 ' %>
        <div class="col-sm-4">
          <%= form.text_field :direccion ,id:"compania" ,class:"form-control" %>
        </div>
      </div>


      <div class="form-group row mb-3">
      <%= form.label 'Proveedor:', class:'col-sm-2 ' %>
      <div class="col-sm-4">
        <%= form.collection_select :proveedor_id,@proveedors,"id","compania",:selected => :id ,class:'form-select'   %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :local,class:'col-sm-2', style: "display: block" %>
      <div class="col-sm-4">
        <%= form.file_field :local, class:'form-control'  %>
        <p></p>
      </div>
      <div class="col-sm-4">
      Imagen del local anterior
      <%= image_tag ubicacion.local,:size => "260x180" %>  
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :mapa,class:'col-sm-2', style: "display: block" %>
      <div class="col-sm-4">
        <%= form.file_field :mapa, class:'form-control'  %>
        <p></p>
      </div>
      <div class="col-sm-4">
      Imagen del mapa anterior
      <%= image_tag ubicacion.mapa,:size => "260x180" %>  
      </div>
    </div>

    
    <button type="submit" name="button" class='btn btn-primary'>
      <span>Guardar</span>
    </button>

    <%= yield(:boton) %>
    <% end %>
</div>

app/views/ubicacions/_ubicacion.html.erb
<div id="<%= dom_id ubicacion %>">

  <div class="card mt-s">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h2 class="text text-secondary text-center ">Proveedor: <%=buscarNombreProveedor(ubicacion.proveedor_id)%></h2>
          <%= image_tag buscarLogoProveedor(ubicacion.proveedor_id) , :size => "260x180" %></td>
      </div>


  <table class=" table table-responsive table-bordered">
    <tr>
      <th>Nombre de la ubicacion</th>
      <td><%=ubicacion.nombre%></td>
    </tr>
    <tr>
      <th>Direccion de la ubicacion</th>
      <td><%=ubicacion.direccion%></td>
    </tr>
    <tr>
      <th>Imagen del local</th>
      <td><%= image_tag ubicacion.local,:size => "260x180" %>  </td>
    </tr>
    <tr>
      <th>Ubicacion en mapa</th>
      <td><%= image_tag ubicacion.mapa,:size => "260x180" %>  </td>
    </tr>
    
  </table>
    


</div>

app/views/ubicacions/edit.html.erb
<h1>Editando ubicacion</h1>

<% content_for :boton do %>
  <%= link_to  "Regresar", ubicacions_path ,class:'btn btn-primary'%>
<% end %>
<%= render "form", ubicacion: @ubicacion  %>

app/views/ubicacions/editDeProveedor.html.erb
<p style="color: green"><%= notice %></p>
<div class="card-header d-flex justify-content-between align-items-center">
  <h3>Editando ubicaciones de <%= buscarNombreProveedor(@var)%></h3>
<%= link_to "Nueva ubicacion" , new_ubicacion_path,  class:"btn btn-primary btn-sm  " %>
</div>

<table class="table table-responsive table-bordered">
  <thead>
    <tr>
      <th>Nombre de ubicacion</th>
      <th>Direccion</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @ubicacionesDelProveedor.each do |ubicacion| %>
      <tr>
          <td>
            <strong><%=  ubicacion.nombre %></strong>
          </td>
          <td>
            <strong><%=  ubicacion.direccion %></strong>
          </td>
          <td>
            <div class="btn-toolbar" role="toolbar">
              <div class="btn-group" role="group">
                <%= button_to image_tag("editar"), edit_ubicacion_path(ubicacion),:method=>:get, :class=>"btn " ,id:"btn-edit" ,:title=>"Editar"%>
                <%= button_to image_tag("trash"), ubicacion, method: :delete ,:class=>"btn " ,id:"btn-ver" ,:title=>"Eliminar" %>
              </div>
            </div>
          </td>

        
      </tr>
    <%end %>
      
  </tbody>
</table>


<div>
  
</div>

app/views/ubicacions/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="card-header d-flex justify-content-between align-items-center">
  <h1>Ubicaciones</h1>
  <%if can? :create, Ubicacion %>
  <%= link_to "Nueva ubicacion" , new_ubicacion_path,  class:"btn btn-primary btn-sm  " %>
  <%end%>
</div>
<br>




<table id="ubicacionesTable" class="table table-striped table-responsive table-bordered">
  <thead>
    <tr>
      <th>Nombre de ubicacion </th>
      <th>Proveedor</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @ubicacions.each do |ubicacion| %>
      <tr>
          <td>
            <strong><%=  ubicacion.nombre %></strong>
          </td>
          <td>
            <strong><%=  buscarNombreProveedor(ubicacion.proveedor_id) %></strong>
          </td>
          <td>
            <div class="btn-toolbar" role="toolbar">
              <div class="btn-group" role="group">
                <%= button_to image_tag("ojo",width:25,height:25), ubicacion,method: :get, :class=>"btn " ,id:"btn-ver" , :title=>"Ver" %>
                <%if can? :update, Ubicacion %>
                <%= button_to image_tag("editar"), edit_ubicacion_path(ubicacion),:method=>:get, :class=>"btn " ,id:"btn-edit" ,:title=>"Editar"%>
                <%end%>
                <%if can? :destroy, Ubicacion %>
                <%= button_to image_tag("trash"), ubicacion, method: :delete ,:class=>"btn " ,id:"btn-ver" ,:title=>"Eliminar" %>
                <%end%>
              </div>
            </div>
          </td>

        
      </tr>
    <%end %>
      
  </tbody>
</table>

<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

  
  <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" media="screen" />
  <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js" type="text/javascript"></script>

  
  <script>
  $(document).ready(function() {
    var oTable = $("#ubicacionesTable").DataTable({
      lengthMenu: [
            [5,10, 25, 50, -1],
            [5,10, 25, 50, 'All'],
        ],
      "language": {
        "lengthMenu": "Mostrar _MENU_ registros",
        "search": "Buscar:",
        zeroRecords: 'No hay registros para mostrar.',
        emptyTable: 'La tabla está vacia.',
        info: "Mostrando _START_ de _END_ de _TOTAL_ Registros.",
        paginate: {
          first: 'Primero',
          previous: 'Anterior',
          next: 'Siguiente',
          last: 'Último'
          }
      }
    })
    
    });
    </script>

app/views/ubicacions/new.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h3 class="text text-secondary">Nueva ubicacion</h3>
</div>
<!-- dentro del archivo q renderise debera venir el card body-->
  <% content_for :boton do %>
    <%= link_to  "Regresar", ubicacions_path ,class:'btn btn-primary'%>
  <% end %> 

<%= render "form", ubicacion: @ubicacion %>

<br>

app/views/ubicacions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ubicacion %>


<div>
<%= link_to  "Regresar", ubicacions_path ,class:'btn btn-primary'%>
  
</div>