config/routes.rb
Rails.application.routes.draw do
  get 'no_user/index'
  get 'tipo_producto/index'
  get 'permiso/index'
  get 'rol/index'
  
  devise_for :views
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :no_user
  resources :tipo_producto
  resources :permiso
  resources :rol
  resources :error404
  resources :usuarios
  resources :references  
  resources :divisions
  resources :cargos
  resources :ubicacions
  get 'ubicacionProveedores/:proveedor_id' , to: 'ubicacions#edit2', :as => 'editUbicacionesProveedor'#sin uso
  get 'proveedor/:usuario_id' , to:'usuarios#nuevoProveedor' , :as => 'proveedorNuevo'
  post 'crearProveedor' , to:'usuarios#crearProveedor',:as =>'crearProveedor'
  get 'ubicacion/:proveedor_id' , to:'usuarios#nuevaUbicacion',:as =>'nuevaUbicacion'
  post 'crearUbicacion' , to:'usuarios#crearUbicacion',:as =>'crearUbicacion'
  get 'referencia/:proveedor_id' , to:'usuarios#nuevaReferencia',:as =>'nuevaReferencia'
  post 'crearReferencia' , to:'usuarios#crearReferencia',:as =>'crearReferencia'
  get 'proveedores/reporte' , to:'proveedors#reporte', :as => 'reporteProveedores'




  
  resources :productos
  resources :linea_requesicions, only: [:index]
  resources :requesicions
  get 'buscador_productos/:criterio', to: 'productos#buscador'
  post 'agregar_producto_requesicion', to: 'requesicions#agregar_producto'
  get 'requesicions/:id/observacion', to: 'requesicions#observacion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :proveedors
  get 'proveedors_user/:id/:usuario_id' , to: 'proveedors#show'
  # Defines the root path route ("/")
  # root "articles#index"
  #resources :cotizacions, only: [:index] rol de proveedor
  resources :linea_cotizacions, only: [:index]
  get 'cotizaciones_proveedor/:id', to: 'cotizacions#new' #rol de proveedor  
  get 'cotizaciones', to: 'cotizacions#evaluar'#rol de autorizador
  get 'cotizaciones_proveedor', to: 'cotizacions#index' #rol de proveedor
  get 'cotizaciones/:id', to: 'cotizacions#detalles' #rol autorizador
  post 'guardar_cotizacion/:id', to: 'cotizacions#create' #rol de proveedor
  post 'guardar_linea_cotizacion', to: 'cotizacions#lineas_cotizacion' #rol de proveedor
  post 'aprobar_cotizacion', to: 'cotizacions#aprobar' #rol autorizador

  get 'reporte/prod_ordenados', to: 'reporg#productos_ordenados'      #reporte por productos ordenados  Gerente
  get 'reporte/compras_categorias', to: 'reporg#compras_categorias'   #Reporte de montos de compra por categorias Gerente
  get 'reporte/stock_productos', to: 'productos#reporte_stock'
  get 'evaluaciones', to: 'evaluacions#index'
  get 'evaluacions/new/:id', to: 'evaluacions#new'
  post 'evaluacions/create', to: 'evaluacions#create'
  resources :login
  get 'login/index', to: 'login#index'

end

app/models/cargo.rb
class Cargo < ApplicationRecord
    has_one :division
    validates_presence_of :nombre,presence:true,:message =>"-> El nombre del cargo debe ser digitado"
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
    before_action :set_cargo, only: %i[ show edit update destroy ]

  # GET /catalogo_cargos or /catalogo_cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /catalogo_cargos/1 or /catalogo_cargos/1.json
  def show
  end

  # GET /catalogo_cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /catalogo_cargos/1/edit
  def edit
  end

  # POST /catalogo_cargos or /catalogo_cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to cargo_url(@cargo), notice: "Catalogo cargo was successfully created." }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogo_cargos/1 or /catalogo_cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to cargo_url(@cargo), notice: "El cargo a sido actualizado correctamente." }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogo_cargos/1 or /catalogo_cargos/1.json
  def destroy
    @cargo.destroy

    respond_to do |format|
      format.html { redirect_to cargos_url, notice: "El cargo a sido eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:nombre)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_cargo.html.erb
<div id="<%= dom_id cargo %>">

  <table class=" table table-responsive table-bordered">
    <tr>
      <th>Nombre cargo</th>
      <td><%=cargo.nombre%></td>
    </tr>
    
  </table>

</div>

app/views/cargos/_form.html.erb
<div class="container ">

  <div class="card-body shadow-lg">
    <%= form_with(model: cargo) do |form| %>
      <div class="form-group row mb-3">
        <% if cargo.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(cargo.errors.count, "error") %> No se puede continuar por los siguientes errores:</h2>

          <ul>
            <% cargo.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
      </div>

      <div class="form-group row mb-3">
        <%= form.label 'Nombre del cargo:', class:'col-sm-2 ' %>
        <div class="col-sm-4">
          <%= form.text_field :nombre , class:'form-control'   %>
        </div>
      </div>
      
      <button type="submit" name="button" class='btn btn-primary btn-sm'>
        <span>Guardar</span>
      </button>
  
      <%= yield(:boton) %>
  
    <% end %> 
  </div>

</div>

app/views/cargos/edit.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h3 class="text text-secondary">Editando cargo</h3>
  </div>
<% content_for :boton do %>
  <%= link_to  "Regresar", cargos_path ,class:'btn btn-primary btn-sm'%>
<% end %>

<%= render "form", cargo: @cargo %>

app/views/cargos/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="card-header d-flex justify-content-between align-items-center">
<h1>Cargos</h1>
<% if can? :create, Cargo %>
<%= link_to "Nuevo cargo" , new_cargo_path,  class:"btn btn-primary btn-sm  " %>
<%end%>
</div>
<br>



<table id="tablaCargos" class="table table-striped table-responsive table-bordered">
  <thead>
    <tr>
      <th>Nombre del cargo </th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
          <td>
            <strong>-<%=  cargo.nombre %></strong>
          </td>
          <td>
            <div class="btn-toolbar" role="toolbar">
              <div class="btn-group" role="group">
                <%= button_to image_tag("ojo",width:25,height:25), cargo,method: :get, :class=>"btn " ,id:"btn-ver" , :title=>"Ver" %>
                <% if can? :update, Cargo %>
                <%= button_to image_tag("editar"), edit_cargo_path(cargo),:method=>:get, :class=>"btn " ,id:"btn-edit" ,:title=>"Editar"%>
                <%end%>
                <% if can? :destroy, Cargo %>
                <%= button_to image_tag("trash"), cargo, method: :delete ,:class=>"btn " ,id:"btn-ver" ,:title=>"Eliminar" %>
                <%end%>
              </div>
            </div>
          </td>

        
      </tr>
    <%end %>
      
  </tbody>
</table>

<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

  
  <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" media="screen" />
  <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js" type="text/javascript"></script>

  
  <script>
  $(document).ready(function() {
    var oTable = $("#tablaCargos").DataTable({
      lengthMenu: [
            [5,10, 25, 50, -1],
            [5,10, 25, 50, 'All'],
        ],
      "language": {
        "lengthMenu": "Mostrar _MENU_ registros",
        "search": "Buscar:",
        zeroRecords: 'No hay registros para mostrar.',
        emptyTable: 'La tabla está vacia.',
        info: "Mostrando _START_ de _END_ de _TOTAL_ Registros.",
        paginate: {
          first: 'Primero',
          previous: 'Anterior',
          next: 'Siguiente',
          last: 'Último'
          }
      }
    })
    
    });
    </script>

app/views/cargos/new.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h3 class="text text-secondary">Nuevo cargo</h3>
    </div>

    <!-- dentro del archivo q renderise debera venir el card body-->
  <% content_for :boton do %>
    <%= link_to  "Regresar", cargos_path ,class:'btn btn-primary btn-sm'%>
  <% end %> 

  <%= render "form", cargo:@cargo %>
</div>

app/views/cargos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cargo %>

<div>
  <%= link_to  "Regresar", cargos_path ,class:'btn btn-primary btn-sm'%>
</div>