config/routes.rb
Rails.application.routes.draw do
  get 'no_user/index'
  get 'tipo_producto/index'
  get 'permiso/index'
  get 'rol/index'
  
  devise_for :views
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :no_user
  resources :tipo_producto
  resources :permiso
  resources :rol
  resources :error404
  resources :usuarios
  resources :references  
  resources :divisions
  resources :cargos
  resources :ubicacions
  get 'ubicacionProveedores/:proveedor_id' , to: 'ubicacions#edit2', :as => 'editUbicacionesProveedor'#sin uso
  get 'proveedor/:usuario_id' , to:'usuarios#nuevoProveedor' , :as => 'proveedorNuevo'
  post 'crearProveedor' , to:'usuarios#crearProveedor',:as =>'crearProveedor'
  get 'ubicacion/:proveedor_id' , to:'usuarios#nuevaUbicacion',:as =>'nuevaUbicacion'
  post 'crearUbicacion' , to:'usuarios#crearUbicacion',:as =>'crearUbicacion'
  get 'referencia/:proveedor_id' , to:'usuarios#nuevaReferencia',:as =>'nuevaReferencia'
  post 'crearReferencia' , to:'usuarios#crearReferencia',:as =>'crearReferencia'
  get 'proveedores/reporte' , to:'proveedors#reporte', :as => 'reporteProveedores'




  
  resources :productos
  resources :linea_requesicions, only: [:index]
  resources :requesicions
  get 'buscador_productos/:criterio', to: 'productos#buscador'
  post 'agregar_producto_requesicion', to: 'requesicions#agregar_producto'
  get 'requesicions/:id/observacion', to: 'requesicions#observacion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :proveedors
  get 'proveedors_user/:id/:usuario_id' , to: 'proveedors#show'
  # Defines the root path route ("/")
  # root "articles#index"
  #resources :cotizacions, only: [:index] rol de proveedor
  resources :linea_cotizacions, only: [:index]
  get 'cotizaciones_proveedor/:id', to: 'cotizacions#new' #rol de proveedor  
  get 'cotizaciones', to: 'cotizacions#evaluar'#rol de autorizador
  get 'cotizaciones_proveedor', to: 'cotizacions#index' #rol de proveedor
  get 'cotizaciones/:id', to: 'cotizacions#detalles' #rol autorizador
  post 'guardar_cotizacion/:id', to: 'cotizacions#create' #rol de proveedor
  post 'guardar_linea_cotizacion', to: 'cotizacions#lineas_cotizacion' #rol de proveedor
  post 'aprobar_cotizacion', to: 'cotizacions#aprobar' #rol autorizador

  get 'reporte/prod_ordenados', to: 'reporg#productos_ordenados'      #reporte por productos ordenados  Gerente
  get 'reporte/compras_categorias', to: 'reporg#compras_categorias'   #Reporte de montos de compra por categorias Gerente
  get 'reporte/stock_productos', to: 'productos#reporte_stock'
  get 'evaluaciones', to: 'evaluacions#index'
  get 'evaluacions/new/:id', to: 'evaluacions#new'
  post 'evaluacions/create', to: 'evaluacions#create'
  resources :login
  get 'login/index', to: 'login#index'

end

app/models/producto.rb
class Producto < ApplicationRecord
    has_many :linea_requesicions
    belongs_to :tipo_producto

    # Imagen del producto
    has_one_attached :imagen

    # Validaciones
    validates_presence_of :nombre, presence: true, :message => "El producto debe tener un nombre"
    validates_presence_of :descripcion, presence: true, :message => "El producto debe tener una descripción"
    validates_presence_of :presentacion, presence: true, :message => "El producto debe tener una presentación"
    validates :precio, numericality: { greater_than_or_equal_to: 0, less_than: BigDecimal(10**6) },
    format: { with: /\A\d{1,3}(\.\d{1,2})?\z/ }
    validates :existencias, numericality: { greater_than_or_equal_to: 0, less_than: BigDecimal(10**6) },
    format: { with: /\A\d{1,3}(\.\d{1,2})?\z/ }
    validates_presence_of :imagen, presence: true, :message => "El producto debe tener una imagen"

    def self.buscador(criterio)
        Producto.where("nombre LIKE ?", "%#{criterio}%")
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  def reporte_stock
    @productos = Producto.all
  end

  def show_image
    @imagen = Producto.find(params[:id])
    send_data @imagen.image, :type => 'image/png',:disposition => 'inline'
  end

  # GET /productos/1 or /productos/1.json
  def show
    @tipo_producto = TipoProducto.find(@producto.tipo_producto_id)
  end

  # GET /productos/new
  def new
    @producto = Producto.new
    @tipo_producto = TipoProducto.all
  end

  # GET /productos/1/edit
  def edit
    @tipo_producto = TipoProducto.all
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)
    @tipo_producto = TipoProducto.all
    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto creado." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto modificado." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto eliminado." }
      format.json { head :no_content }
    end
  end

  def buscador
    @resultados = Producto.buscador(params[:criterio]).map do |producto|
      {
        id: producto.id,
        nombre: producto.nombre,
        existencia: producto.existencias
      }
    end

    respond_to do |format|
      format.json { render :json => @resultados }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:imagen, :nombre, :descripcion, :presentacion, :precio, :existencias, :tipo_producto_id)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
 <div class="container">
  <%= form_with(model: producto) do |form| %>
    <% if producto.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

        <ul>
          <% producto.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.label 'Tipo de producto:'%>
    <%= form.collection_select :tipo_producto_id,@tipo_producto,"id","nombre",:selected => :id, class:'form-select' %>
    <div>
    <%= form.label 'Nombre del producto:'%>
    <%= form.text_field :nombre, class: 'form-control' %>
    <%= form.label 'Descripción:' %>
    <%= form.text_field :descripcion, class: 'form-control' %>
    <%= form.label 'Presentación:' %>
    <%= form.text_field :presentacion, class: 'form-control' %>
    <%= form.label 'Precio:' %>
    <%= form.number_field :precio, value: @producto.precio ? number_with_precision(@producto.precio, precision: 2) : nil, min: 0, step:0.01, class: 'form-control' %>
    <%= form.label 'Existencias:' %>
    <%= form.number_field :existencias, value: @producto.existencias ? number_with_precision(@producto.existencias, precision: 2) : nil, min: 0, step:0.01, class: 'form-control' %>
    <%= form.label 'Imagen:' %>
    <%= form.file_field :imagen, accept: 'image/png, image/jpeg', class: 'form-control' %>
    </div>
    <br>
    <button type="submit" name="button" class='btn btn-success'>
      <span>Guardar</span>
    </button>

    <%= yield(:botonret) %>
  <% end %>
</div>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
    <table class="table table-responsive">
        <colgroup>
            <col span="1" style="width: 35%">
            <col span="1" style="width: 65%">
        </colgroup>
        <thead>
            <th colspan="2" style="text-align:center;">
                <%= image_tag producto.imagen , :size => "200x200" %>
            </th>
        </thead>
        <tbody>
            <tr>
                <td>Nombre del producto:</td>
                <td><%= producto.nombre %></td>
            </tr>
            <tr>
                <td>Descripción:</td>
                <td><%= producto.descripcion %></td>
            </tr>
            <tr>
                <td>Presentación:</td>
                <td><%= producto.presentacion %></td>
            </tr>
            <tr>
                <td>Precio:</td>
                <td>$<%= producto.precio %></td>
            </tr>
            <tr>
                <td>Existencias:</td>
                <td><%= producto.existencias %></td>
            </tr>
        </tbody>
    </table>
</div>

app/views/productos/edit.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h1 class="text text-secondary">Editar producto</h1>
  </div>
    <% content_for :botonret do %>
      <%= link_to "Regresar", productos_path, class: 'btn btn-primary' %>
    <% end %>

    <%= render "form", producto: @producto %>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="card-header d-flex justify-content-between align-items-center">
  <h1>Productos</h1>
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group" role="group">
      <% if can? :create, Producto %>
      <%= link_to "Agregar producto", new_producto_path, class:"btn btn-primary btn-sm" %>
      <% end %>
      <br>
      <% if can? :reporte_stock, Producto%>
      <%= link_to "Reporte de Stock","reporte/stock_productos", class:"btn btn-info btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

<table id="productos_tabla" class="table table-striped table-responsive table-bordered table-sm">
  <colgroup>
    <col span="1" style="width: 8%;">
    <col span="1" style="width: 50%;">
    <col span="1" style="width: 15%;">
    <col span="1" style="width: 15%;">
    <col span="1" style="width: 12%;">
  </colgroup>
  <thead>
    <th></th>
    <th>Producto </th>
    <th>Precio Unitario</th>
    <th>Existencias</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td style="text-align:center;"><img src="<%= (url_for(producto.imagen)) %>" style="width: 48px; height: 48px;"></td>
        <td>
          <strong title="<%= producto.descripcion %>"><%= producto.nombre %></strong>
          <br>
          <%= producto.presentacion %>
        </td>
        <td style="text-align:right;">$<%= producto.precio %></td>
        <td style="text-align:right;"><%= producto.existencias %></td>
        <td>
          <div class="btn-toolbar" role="toolbar">
            <div class="btn-group" role="group">
              <%= button_to image_tag("ojo",width:25,height:25), producto,method: :get, :class=>"btn " ,id:"btn-ver" , :title=>"Ver" %>
              <% if can? :update, Producto %>
              <%= button_to image_tag("editar"), edit_producto_path(producto),:method=>:get, :class=>"btn " ,id:"btn-edit" ,:title=>"Editar"%>
              <%end%>
              <% if can? :destroy, Producto %>
              <%= button_to image_tag("trash"), producto, method: :delete ,:class=>"btn " ,id:"btn-ver" ,:title=>"Eliminar" %>
              <%end%>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/productos/new.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h1 class="text text-secondary">Agregar producto</h1>
  </div>
    <% content_for :botonret do %>
      <%= link_to "Regresar", productos_path, class: 'btn btn-primary' %>
    <% end %>

    <%= render "form", producto: @producto %>
</div>

app/views/productos/reporte_stock.html.erb
<div class="card-header d-flex justify-content-between align-items-center">
  <%= link_to "Regresar", productos_path, class:"btn btn-primary btn-sm"%>
  <h1>Reporte de Stock</h1>
</div>

<table class="table table-responsive table-bordered">
    <thead>
        <th>#</th>
        <th>Producto</th>
        <th>Presentación</th>
        <th>Existencias</th>
    </thead>
    <tbody>
        <% @productos.each do |producto| %>
            <tr>
                <td><%= producto.id %></td>
                <td><%= producto.nombre %></td>
                <td><%= producto.presentacion %></td>
                <td><%= producto.existencias %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group" role="group">
    <%= button_to "❮ Regresar", productos_path,:class=>"btn btn-secondary" %>
    <% if can? :update, Producto %>
    <%= button_to image_tag("editar"), edit_producto_path(@producto),:method=>:get, :class=>"btn " ,id:"btn-edit" ,:title=>"Editar"%>
    <%end%>
    <% if can? :destroy, Producto %>
    <%= button_to image_tag("trash"), @producto, method: :delete ,:class=>"btn " ,id:"btn-ver" ,:title=>"Eliminar" %>
    <%end%>
  </div>
</div>