config/routes.rb
Rails.application.routes.draw do
  get 'no_user/index'
  get 'tipo_producto/index'
  get 'permiso/index'
  get 'rol/index'
  
  devise_for :views
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :no_user
  resources :tipo_producto
  resources :permiso
  resources :rol
  resources :error404
  resources :usuarios
  resources :references  
  resources :divisions
  resources :cargos
  resources :ubicacions
  get 'ubicacionProveedores/:proveedor_id' , to: 'ubicacions#edit2', :as => 'editUbicacionesProveedor'#sin uso
  get 'proveedor/:usuario_id' , to:'usuarios#nuevoProveedor' , :as => 'proveedorNuevo'
  post 'crearProveedor' , to:'usuarios#crearProveedor',:as =>'crearProveedor'
  get 'ubicacion/:proveedor_id' , to:'usuarios#nuevaUbicacion',:as =>'nuevaUbicacion'
  post 'crearUbicacion' , to:'usuarios#crearUbicacion',:as =>'crearUbicacion'
  get 'referencia/:proveedor_id' , to:'usuarios#nuevaReferencia',:as =>'nuevaReferencia'
  post 'crearReferencia' , to:'usuarios#crearReferencia',:as =>'crearReferencia'
  get 'proveedores/reporte' , to:'proveedors#reporte', :as => 'reporteProveedores'




  
  resources :productos
  resources :linea_requesicions, only: [:index]
  resources :requesicions
  get 'buscador_productos/:criterio', to: 'productos#buscador'
  post 'agregar_producto_requesicion', to: 'requesicions#agregar_producto'
  get 'requesicions/:id/observacion', to: 'requesicions#observacion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :proveedors
  get 'proveedors_user/:id/:usuario_id' , to: 'proveedors#show'
  # Defines the root path route ("/")
  # root "articles#index"
  #resources :cotizacions, only: [:index] rol de proveedor
  resources :linea_cotizacions, only: [:index]
  get 'cotizaciones_proveedor/:id', to: 'cotizacions#new' #rol de proveedor  
  get 'cotizaciones', to: 'cotizacions#evaluar'#rol de autorizador
  get 'cotizaciones_proveedor', to: 'cotizacions#index' #rol de proveedor
  get 'cotizaciones/:id', to: 'cotizacions#detalles' #rol autorizador
  post 'guardar_cotizacion/:id', to: 'cotizacions#create' #rol de proveedor
  post 'guardar_linea_cotizacion', to: 'cotizacions#lineas_cotizacion' #rol de proveedor
  post 'aprobar_cotizacion', to: 'cotizacions#aprobar' #rol autorizador

  get 'reporte/prod_ordenados', to: 'reporg#productos_ordenados'      #reporte por productos ordenados  Gerente
  get 'reporte/compras_categorias', to: 'reporg#compras_categorias'   #Reporte de montos de compra por categorias Gerente
  get 'reporte/stock_productos', to: 'productos#reporte_stock'
  get 'evaluaciones', to: 'evaluacions#index'
  get 'evaluacions/new/:id', to: 'evaluacions#new'
  post 'evaluacions/create', to: 'evaluacions#create'
  resources :login
  get 'login/index', to: 'login#index'

end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :proveedor

  validates_presence_of :nombre_entidad,presence:true,:message =>"-> El nombre de la entidad debe ser digitado"
  validates_presence_of :nombre_contacto,presence:true,:message =>"-> El nombre de contacto  debe ser digitado"
  validates_format_of :telefono_contacto, :with => /\A[0-9]{4}\s[0-9]{4}\Z/, :message => "el formato debe ser  2777 7777 "
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
    before_action :set_reference, only: %i[ show edit update destroy ]

  # GET /referencia_proveedors or /referencia_proveedors.json
  def index
    @references = Reference.all
  end

  # GET /references/1 or /references/1.json
  def show
  end

  # GET /reference/new
  def new
    @reference = Reference.new
    @proveedors= Proveedor.all
  end

  # GET /referencia_proveedors/1/edit
  def edit
    @proveedors= Proveedor.all
  end

  # POST /referencia_proveedors or /referencia_proveedors.json
  def create
    @reference = Reference.new(reference_params)
    @proveedors= Proveedor.all
    respond_to do |format|
      if @reference.save
        format.html { redirect_to reference_url(@reference), notice: "La referencia al proveedor a sido creada." }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referencia_proveedors/1 or /referencia_proveedors/1.json
  def update
    @proveedors= Proveedor.all
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to reference_url(@reference), notice: "La referencia a sido actualizada." }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referencia_proveedors/1 or /referencia_proveedors/1.json
  def destroy
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url, notice: "La referencia da sido eliminada" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reference_params
      params.require(:reference).permit(:nombre_entidad, :nombre_contacto, :telefono_contacto, :proveedor_id)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper

    def buscarCompania(id)
        val=(Proveedor.find(id)).compania
    end

    
end

app/views/references/_form.html.erb
<div class="container ">
    <div class="card-body shadow-lg">
        <%= form_with(model: reference) do |form| %>
          <div class="form-group row mb-3">
            <% if reference.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(reference.errors.count, "error") %> No se puede continuar por los siguientes errores:</h2>

                <ul>
                  <% reference.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div>
          
          <div class="form-group row mb-3">
            <%= form.label 'Nombre_entidad:', class:'col-sm-2 ' %>
            <div class="col-sm-4">
            <%= form.text_field :nombre_entidad , class:'form-control' %>

            </div>
          </div>

          <div class="form-group row mb-3">
            <%= form.label 'Nombre_contacto:', class:'col-sm-2 ' %>
            <div class="col-sm-4">
            <%= form.text_field :nombre_contacto , class:'form-control' %>

            </div>
          </div>

          <div class="form-group row mb-3">
            <%= form.label 'Telefono:', class:'col-sm-2 ' %>
            <div class="col-sm-4">
            <%= form.text_field :telefono_contacto , class:'form-control' %>

            </div>
          </div>

          <div class="form-group row mb-3">
            <%= form.label 'Proveedor:', class:'col-sm-2 ' %>
            <div class="col-sm-4">
            <%= form.collection_select :proveedor_id,@proveedors,"id","compania",class:'form-select' %>

            </div>
          </div>

          

          <button type="submit" name="button" class='btn btn-primary'>
            <span>Guardar</span>
          </button>

          <%= yield(:boton) %>
        <% end %>
      </div>
 </div>

app/views/references/_reference.html.erb
<div id="<%= dom_id reference %>">

  <table class=" table table-responsive table-bordered">
    <tr>
      <th>Nombre entidad</th>
      <td><%=reference.nombre_entidad%></td>
    </tr>
    
    <tr>
      <th>Nombre contacto</th>
      <td><%=reference.nombre_contacto%></td>
    </tr>

    <tr>
      <th>Telefono</th>
      <td><%=reference.telefono_contacto%></td>
    </tr>

    <tr>
      <th>Proveedor</th>
      <td><%=buscarCompania(reference.proveedor_id)%></td>
    </tr>
    
    

  </table>

</div>

app/views/references/edit.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
  <h3 class="text text-secondary">Editando referencia a <%= buscarCompania(@reference.proveedor_id)%> </h3>
  </div>
  
  <% content_for :boton do %>
    <%= link_to  "Regresar", references_path ,class:'btn btn-primary'%>
  <% end %>

  <%= render "form", reference: @reference %>

app/views/references/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="card-header d-flex justify-content-between align-items-center">
  <h1>Referencias</h1>
  <%if can? :create, Reference %>
  <%= link_to "Nueva referencia" , new_reference_path,  class:"btn btn-primary btn-sm  " %>
  <%end%>
</div>
<br>

<table id="referenciasTabla"class="table table-striped table-responsive table-bordered">
  <thead>
    <tr>
      <th>Entidad </th>
      <th>Proveedor referenciado</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @references.each do |reference| %>
      <tr>
          <td>
            <strong><%=  reference.nombre_entidad %></strong>
          </td>
          <td>
            <strong><%=  buscarCompania(reference.proveedor_id) %></strong>
          </td>
          <td>
            <div class="btn-toolbar" role="toolbar">
              <div class="btn-group" role="group">
                <%= button_to image_tag("ojo",width:25,height:25), reference,method: :get, :class=>"btn " ,id:"btn-ver" , :title=>"Ver" %>
                <%if can? :update, Reference %>
                <%= button_to image_tag("editar"), edit_reference_path(reference),:method=>:get, :class=>"btn " ,id:"btn-edit" ,:title=>"Editar"%>
                <%end%>
                <%if can? :destroy, Reference %>
                <%= button_to image_tag("trash"), reference, method: :delete ,:class=>"btn " ,id:"btn-ver" ,:title=>"Eliminar" %>
                <%end%>
              </div>
            </div>
          </td>

        
      </tr>
    <%end %>
      
  </tbody>
</table>


<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

  
  <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" media="screen" />
  <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js" type="text/javascript"></script>

  
  <script>
  $(document).ready(function() {
    var oTable = $("#referenciasTabla").DataTable({
      lengthMenu: [
            [5,10, 25, 50, -1],
            [5,10, 25, 50, 'All'],
        ],
      "language": {
        "lengthMenu": "Mostrar _MENU_ registros",
        "search": "Buscar:",
        zeroRecords: 'No hay registros para mostrar.',
        emptyTable: 'La tabla está vacia.',
        info: "Mostrando _START_ de _END_ de _TOTAL_ Registros.",
        paginate: {
          first: 'Primero',
          previous: 'Anterior',
          next: 'Siguiente',
          last: 'Último'
          }
      }
    })
    
    });
    </script>

app/views/references/new.html.erb
<div class="card mt-s">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h3 class="text text-secondary">Nueva referencia a proveedor</h3>  
  </div>
  <!-- dentro del archivo q renderise debera venir el card body-->
  <% content_for :boton do %>
    <%= link_to  "Regresar", references_path ,class:'btn btn-primary'%>
  <% end %> 
    <%= render "form", reference: @reference %>

    

app/views/references/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reference %>

<%= link_to  "Regresar", references_path ,class:'btn btn-primary'%>